name: Node.js CD

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        script: |
          cd ./sport-server
          git pull origin master
          npm i
          rm -rf ./dist
          npm run build
          pm2 restart main
